export const initialPayments = [
  { name: "Fondi regionali", amount: 18000 },
  { name: "Mario Floris", amount: 200 },
  { name: "Daniela Serra", amount: 100 },
  { name: "Pietro Fais", amount: 80 },
  { name: "Nicola Rossi", amount: 50 },
  { name: "Cinzia Montisci", amount: 10 },
  { name: "Sonia Carta", amount: 10 },
  { name: "Laura Rossi", amount: 150 },
  { name: "Roberto Bianchi", amount: 120 },
  { name: "Elisa Verdi", amount: 90 },
  { name: "Alessandro Neri", amount: 70 },
  { name: "Giorgio Gialli", amount: 40 },
  { name: "Simone Ferrari", amount: 170 },
  { name: "Giulia Russo", amount: 110 },
  { name: "Marco Esposito", amount: 85 },
  { name: "Sara Romano", amount: 65 },
  { name: "Davide Martini", amount: 45 },
];
